version: "3.8"

services:
  database:
    build:
      context: database
    restart: always
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_DB=db-archimanager
    ports:
      - 5432
    secrets:
      - db-user
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - private

  gui:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=pierrot.sylvain14@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    networks:
      - private
    depends_on:
      - database

  frontend:
    build:
      context: frontend
      target: dev
    restart: always
    ports:
      - 8080:8080
    networks:
      - public
    depends_on:
      - database
      - backend

  backend:
    build:
      context: backend
    environment:
      - NODE_ENV=developpemnt
    restart: always
    ports:
      - 5000:5000
    networks:
      - public
      - private
    depends_on:
      - database

volumes:
  db-data:

networks:
  public:
  private:

secrets:
  db-user:
    file: database/user.txt
  db-password:
    file: database/password.txt
