version: "3.8"

services:
  db:
    build:
      context: .
    restart: always
    environment:
      - POSTGRES_USER_FILE=/run/secrets/db-user
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
      - POSTGRES_DB=db-archimanager
    ports:
      - 5432
    secrets:
      - db-user
      - db-password
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - private

  gui:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=pierrot.sylvain14@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    networks:
      - private
    depends_on:
      - db

  front-end:
    build:
      context: front-end
    restart: always
    ports:
      - 8080:8080
    networks:
      - public

  back-end:
    build:
      context: back-end
    restart: always
    ports:
      - 5000
    networks:
      - public
      - private
    depends_on:
      - db
      - gui

volumes:
  db-data:

networks:
  public:
  private:

secrets:
  db-user:
    file: db/user.txt
  db-password:
    file: db/password.txt
